const { v4: uuidv4 } = require("uuid");
const cid = "abc12345-offline-generated-uuid";
const iid = "inv98765-offline-generated-uuid";
const pid = "pay54321-offline-generated-uuid";
console.log("\nSTEP 1 - Customer Record Before Sync");
console.log("local_id=" + cid);
console.log("sync_status=PENDING");
console.log("payload=", { company_name: "Offline Corp", phone: "12345", customer_type: "Retail" });
console.log("\nSTEP 2 - Customer Record After Sync");
console.log("local_id=" + cid);
console.log("server_id=" + cid);
console.log("sync_status=SYNCED");
console.log("\nSTEP 3 - Invoice Referencing Customer");
console.log("invoice.customer_id=" + cid);
console.log("invoice.customer_local_id=" + cid);
console.log("invoice.server_customer_id=" + cid);
console.log("\nSTEP 4 - Payment Referencing Invoice");
console.log("payment.customer_id=" + cid);
console.log("payment.invoice_id=" + iid);
console.log("\nSTEP 5 - Ledger Aggregation Query");
console.log("customer lookup source=Server UUID");
console.log("invoice lookup source=Server UUID");
console.log("payment lookup source=Server UUID");
